### ISSUE TITLE
Rebuild of org.kde.Sdk is broken

### ISSUE THREAD

**Issue by aleixpol** [flathub/flathub#1745]
```
git fetch -t https://github.com/flathub/flatpak-kde-runtime qt5.14 --progress
 in dir /srv/buildbot-master/master/workers/MasterWorker6/Builds/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'fetch', b'-t', b'https://github.com/flathub/flatpak-kde-runtime', b'qt5.14', b'--progress']
 using PTY: False
fatal: could not read Username for 'https://github.com': No such device or address
program finished with exit code 128
```

As seen in https://flathub.org/builds/#/builders/32/builds/25322

The fetched url should be https://invent.kde.org/packaging/flatpak-kde-runtime.git

**Comment by tsdgeos** [comment]
Aleix it seems you broke it in https://github.com/flathub/buildbot-config/commit/53f51d07d58f1287f49e821d5c25d50045c54325#diff-af30a0fe84e0ca8530215e0630e3ac89

Fixed in https://github.com/flathub/buildbot-config/commit/6094e58e7e979637b589a226eac62d500c9dd0f7

**Comment by nedrichards** [comment]
Seems still broken https://flathub.org/builds/#/builders/32/builds/25493 @barthalion may need to do more investigation since that *should* work.

**Comment by nedrichards** [comment]
Ah, the power of "turn it off and on again" https://flathub.org/builds/#/builders/32/builds/25499
