### ISSUE TITLE
appstream metadata badly formatted when using `<em>` in the description

### ISSUE THREAD

**Issue by abique** [flathub/flathub#3099]
Hi,

As you can see in the description of Bitwig Studio: https://flathub.org/apps/details/com.bitwig.BitwigStudio there is `<em>Make music.</em>`.

While according to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description `<em>` is allowed within `<description>`.

Bitwig Studio's xml is correctly formatted, but when aggregated into: `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml` then the chunk is escaped: `&lt;em&gt;Make music.&lt;/em&gt;`.

**Comment by abique** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://www.freedesktop.org/software/appstream/docs/ -->
<!-- Copyright 2022 Bitwig GmbH -->
<component type="desktop">
  <id>com.bitwig.BitwigStudio</id>
  <metadata_license>MIT</metadata_license>
  <project_license>LicenseRef-proprietary</project_license>
  <name>Bitwig Studio</name>
  <developer_name>Bitwig GmbH</developer_name>
  <summary>Modern music production and performance</summary>
  <description>
    <p>Bitwig Studio is a digital audio workstation (DAW) that inspires you to take greater control of your music,
    giving you access to every aspect of your production. Streamline your creative process and quickly evolve your
    ideas into complete songs, tracks, and compositions. Record and arrange, improvise and perform, or do it all at once.
    Design sounds. Build instruments. <em>Make music.</em></p>
  </description>
  <screenshots>
    <screenshot type="default">
      <image>https://www.bitwig.com/media/image/bitwig-home_2111_bws-4_lg/Bitwig-Home_2111_BWS-4_LG-SD.png</image>
      <caption>Bitwig Studio</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_screenshot-record-and-arrange/Bitwig-BWS4_Screenshot-Record-and-Arrange.png</image>
      <caption>Bitwig Arranger</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_screenshot-improvise-and-perform/Bitwig-BWS4_Screenshot-Improvise-and-Perform.png</image>
      <caption>Bitwig Mixer</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_screenshot-design-sounds/Bitwig-BWS4_Screenshot-Design-Sounds.png</image>
      <caption>Sound Design</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_audio-editing_full/Bitwig-BWS4_Audio-Editing_full_3.png</image>
      <caption>Audio Editing</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_screenshot-expressive-midi_full/Bitwig-BWS4_Screenshot-Expressive-MIDI_full.png</image>
      <caption>Expressive MIDI Support</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws4_time-stretching_full/Bitwig-BWS4_Time-Stretching_full.png</image>
      <caption>Time-Stretching</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-studio-bws3_modulators_2/Bitwig-Studio-BWS3_Modulators_2.png</image>
      <caption>Modulation Heaven</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig_bws3-1_hw_integration/Bitwig_BWS3-1_HW-Integration.png</image>
      <caption>Hardware Integration</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws3-2_enter-the-grid/Bitwig-BWS3-2_Enter-the-Grid.png</image>
      <caption>Enter The Grid</caption>
    </screenshot>
    <screenshot>
      <image>https://www.bitwig.com/media/image/bitwig-bws3-2_sampler-main/Bitwig-BWS3-2_Sampler-Main.png</image>
      <caption>Sampler, Resampled</caption>
    </screenshot>
  </screenshots>
  <content_rating type="oars-1.1" />
  <recommends>
    <memory>4096</memory> <!-- recommend at least 4GiB of memory -->
  </recommends>
  <supports>
    <control>keyboard</control>
    <control>pointing</control>
    <control>touch</control>
    <display_length compare="ge">medium</display_length>
  </supports>
  <update_contact>support@bitwig.com</update_contact>
  <url type="homepage">https://www.bitwig.com/</url>
  <url type="help">https://www.bitwig.com/learn/</url>
  <url type="faq">https://www.bitwig.com/support/</url>
  <url type="contact">https://www.bitwig.com/contact/</url>
  <releases>
    <release version="4.2.3" date="2022-04-06" />
  </releases>
  <provides>
    <mediatype>application/bitwig-project</mediatype>
    <mediatype>application/bitwig-clip</mediatype>
    <mediatype>application/bitwig-scene</mediatype>
    <mediatype>application/bitwig-device</mediatype>
    <mediatype>application/bitwig-module</mediatype>
    <mediatype>application/bitwig-modulator</mediatype>
    <mediatype>application/bitwig-preset</mediatype>
    <mediatype>application/bitwig-template</mediatype>
    <mediatype>application/bitwig-package</mediatype>
    <mediatype>application/bitwig-extension</mediatype>
    <mediatype>application/bitwig-remote-controls</mediatype>
  </provides>
</component>
```

**Comment by JakobDev** [comment]
This is a known problem. The reason for this Problem is, that Flatpak currently uses appstream-glib for dealing with Appstream data. appstream-glib is older Lib which is known to have Problems especially with newer Appstream versions. This and lot of other Appstream related problems will be fixed when flatpak/flatpak-builder#418 is finally merged. But unfortunally it looks like it will take some time until it is merged.

**Comment by abique** [comment]
Thank you for the feedback!
Good luck with the other issue.

I guess we should close this issue then? That's up to you.

**Comment by zecakeh** [comment]
I am wondering what is the status of this? There is a similar issue on the website repo (https://github.com/flathub/website/issues/131) that was closed because it was deemed fixed.

However I can still see the `<em>` tags on the website. For example in [Fractal](https://flathub.org/fr/apps/org.gnome.Fractal)'s release notes or [Openshot](https://flathub.org/fr/apps/org.openshot.OpenShot)'s description.

**Comment by razzeee** [comment]
The change was rolled back due to general problems back then and hasn't been rolled out again.

**Comment by JakobDev** [comment]
@razzeee Any estimated time for when libappstream is rolled out again?

**Comment by razzeee** [comment]
I don't think there is

**Comment by razzeee** [comment]
Rebuilding apps should allow `em` tags to work

**Comment by bbhtt** [comment]
code and em should work now

See https://github.com/flathub/dev.k8slens.OpenLens/blob/6a86fee5dc65537ecbeb9d2a42dfda5c7c144cd5/dev.k8slens.OpenLens.metainfo.xml#L19-L20

and on the website https://flathub.org/apps/dev.k8slens.OpenLens

**Comment by ztefn** [comment]
`em` tags are still broken for translated descriptions.

[Original (English)](https://flathub.org/apps/com.github.ztefn.haguichi):
`Please note: Requires installation of Hamachi on the system in order to use.`

[Dutch](https://flathub.org/nl/apps/com.github.ztefn.haguichi):
`<em>Let op: Vereist installatie van Hamachi op het systeem om volledig te kunnen gebruiken.</em>`
