### ISSUE TITLE
Enable automatic branch deletion when a PR is merged for all KDE Apps repos

### ISSUE THREAD

**Issue by travier** [flathub/flathub#3157]
Hey folks, thanks for all the good work you're doing with Flathub!

Could an admin take a look at KDE repos on Flathub (the one maintained by the KDE team) and enable automatic branch deletion when a PR is merged for those where it is missing? New ones have it but older ones don't.

There might even be an automated way to do that via the GitHub API.

Thanks!

**Comment by travier** [comment]
Hopefully exhaustive list of the repos that need this change:
- [ ] https://github.com/flathub/org.kde.kile
- [ ] https://github.com/flathub/org.kde.okular
- [ ] https://github.com/flathub/org.kde.umbrello
- [ ] https://github.com/flathub/org.kde.kopete
- [ ] https://github.com/flathub/org.kde.pix
- [ ] https://github.com/flathub/org.kde.kuiviewer
- [ ] https://github.com/flathub/org.kde.akregator
- [ ] https://github.com/flathub/org.kde.kphotoalbum
- [ ] https://github.com/flathub/org.kde.filelight
- [ ] https://github.com/flathub/org.kde.kget
- [ ] https://github.com/flathub/org.kde.kcachegrind
- [ ] https://github.com/flathub/org.kde.krdc
- [ ] https://github.com/flathub/org.kde.kruler
- [ ] https://github.com/flathub/org.kde.ktorrent
- [ ] https://github.com/flathub/org.kde.kbreakout
- [ ] https://github.com/flathub/org.kde.kfourinline
- [ ] https://github.com/flathub/org.kde.kiriki
- [ ] https://github.com/flathub/org.kde.falkon
- [ ] https://github.com/flathub/org.kde.kcolorchooser
- [ ] https://github.com/flathub/org.kde.kcalc
- [ ] https://github.com/flathub/org.kde.kdf
- [ ] https://github.com/flathub/org.kde.kfind
- [ ] https://github.com/flathub/org.kde.okteta

**Comment by bilelmoussaoui** [comment]
Done

**Comment by travier** [comment]
Thanks!

**Comment by Justinzobel** [comment]
A few more that need the auto delete branch setting added, thanks!

- [ ] https://github.com/flathub/org.kde.labplot2
- [ ] https://github.com/flathub/org.kde.itinerary
- [ ] https://github.com/flathub/org.kde.kbibtex
- [ ] https://github.com/flathub/org.kde.tellico

**Comment by bilelmoussaoui** [comment]
@travier @Justinzobel both should be done now

**Comment by Justinzobel** [comment]
Thanks!

**Comment by Justinzobel** [comment]
Two more please:
- [ ] https://github.com/flathub/org.kde.plasmatube
- [ ] https://github.com/flathub/org.kde.atlantik

**Comment by bbhtt** [comment]
Done, please ping if I missed any.

**Comment by travier** [comment]
Hey folks, we still have a lot of repos without this setting set. As it's probably painful to set it manually, I've made a script to do it for all our repos:

```
$ git clone https://invent.kde.org/ravier/flathub-maintenance-scripts.git
$ cd flathub-maintenance-scripts
# Write GitHub token with settings access to Flathub repos in `.githuub-token`
$ ./kde_set_delete_branch_on_merge.sh
```

Thanks

CC @bbhtt

**Comment by bbhtt** [comment]
I have turned it on by default for new merges https://github.com/flathub/flathub/commit/5b657a2de5b8837e351b91bea6e83f51e8000490

I'll enable it for org.kde. repos shortly.

**Comment by bbhtt** [comment]
Should be handled now, let me know if anything is missing it.

**Comment by travier** [comment]
Thanks!

**Comment by travier** [comment]
We missed: https://github.com/flathub/org.gtk.Gtk3theme.Breeze

**Comment by bbhtt** [comment]
Enabled
