### ISSUE TITLE
Mesa 22 not working with AMD RX 7000 series cards

### ISSUE THREAD

**Issue by majewsky** [flathub/flathub#3845]
This is my current package selection (just obs-studio plus dependencies and an addon from a non-Flathub repo). This should be fully up-to-date as of right now, I did a `flatpak update && flatpak uninstall --unused` right before.

```
$ flatpak list
Name                               Application ID                                  Version          Branch               Origin                   Installation
OBS Studio                         com.obsproject.Studio                           29.0.0           stable               flathub                  user
StreamFX                           com.obsproject.Studio.Plugin.StreamFX                            stable               streamfx-origin          user
Mesa                               org.freedesktop.Platform.GL.default             22.3.2           22.08                flathub                  user
Mesa (Extra)                       org.freedesktop.Platform.GL.default             22.3.2           22.08-extra          flathub                  user
openh264                           org.freedesktop.Platform.openh264               2.1.0            2.2.0                flathub                  user
Adwaita dark GTK theme             org.gtk.Gtk3theme.Adwaita-dark                                   3.22                 flathub                  user
KDE Application Platform           org.kde.Platform                                                 6.4                  flathub                  user
```

I recently purchased a new GPU (an AMD RX 7900 XT). This GPU is supported by Mesa 22, but *only* when compiled against LLVM 15 or later. I know this for a fact because Arch Linux only pushed the LLVM 15 update a few days after I first tried to setup the GPU. With Mesa 22 compiled against LLVM 14, the GPU fully entirely does not work.

Unfortunately, Flathub's current Mesa is compiled against LLVM 14:

```
$ find ~/.local/share/flatpak/ -iname \*llvm\*
/home/stefan/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/22.08-extra/4c6ff4f8c2418f647a814fd14d8c7500d1de7bfd14f10c192eb96a9f638762cf/files/lib/libLLVM-14.so
/home/stefan/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/22.08/bf66cf0adc4293974c628834984b689549fb0906036f6af7bbc62f4d458d516a/files/lib/libLLVM-14.so
```

In OBS Studio, this manifests as Pipewire screen capture sources not working. Could you please recompile Mesa against LLVM 15?

**Comment by doraskayo** [comment]
This should be fixed by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/11343 for 22.08, but requires tagging a version to reach Flathub. Hopefully not too long until that happens.

**Comment by majewsky** [comment]
LLVM 15 has hit the stable channel, and unfortunately this has not resolved the issue. However, I have since reproduced the issue with the obs-studio version packaged by Arch Linux, so I'm moving this issue to obs-studio: https://github.com/obsproject/obs-studio/issues/8170

**Comment by doraskayo** [comment]
Note that the last update was released and quickly reverted due to a regression surrounding Mesa. The issue was found, so update should be released again soon.
