### ISSUE TITLE
gnome 42 sdk fail to download on builders.

### ISSUE THREAD

**Issue by hfiguiere** [flathub/flathub#3888]
Similiar to #3870 

`Error: Failed to update org.gnome.Sdk: While pulling runtime/org.gnome.Sdk/x86_64/42 from remote flathub: URI https://dl.flathub.org/repo/deltas/Uw/jJdOTHWwhx3KQfqMrGnz1eC5d1odXxnfcUZcCVTzM-eEIBJAFF86RU0e2rOGhGhsR_OEBrnGb422ccX4wdk0A/6 exceeded maximum size of 1712497 bytes`

See
https://buildbot.flathub.org/#/builders/6/builds/21392

**Comment by barthalion** [comment]
Fixed.

**Comment by hfiguiere** [comment]
Actually it is still happening. Happened on my own machine with the exact same error.

**Comment by brokenshield** [comment]
> Actually it is still happening. Happened on my own machine with the exact same error.

Same for me (tried again at 22:45 GMT today). As I'm no expert, if this is not the correct place to post about the issue could someone point me at the correct place? 

Thanks to all the developers for their hard work in general on Gnome and flatpaks.
