### ISSUE TITLE
Quality guideline problems for DevilutionX

### ISSUE THREAD

**Issue by tsunamistate** [flathub/flathub#6150]
### Flathub store page link

https://flathub.org/apps/org.diasurgical.DevilutionX

### Questions or Feedback

* Branding
       * Has primary branding colours: will these colours be OK?

![Image](https://github.com/user-attachments/assets/cdba4099-bf4f-44aa-acc7-8513719395f2)

* App icon
  * Doesn't fill too much or too little of the canvas: I don't get it, please help
  * Good contrast on dark backgrounds: Don't get this either, icon has good contrast already
* App name
  * No weird formatting, punctuation, lowercase, etc.: I would like to ask for branding exception. DevilutionX is named this was to differentiate from [Devilution](https://github.com/diasurgical/devilution), which is bit-compatible reverse-engineered source code of Diablo, and Devilutionx doesn't look as good, IMO
* Summary
  * Understandable for a non-technical person: Should I change "source port" to "build", like in GitHub description?

Will close https://github.com/diasurgical/devilutionX/issues/7746

**Comment by bertob** [comment]
Maybe you could add a space to the name, i.e. "Devilution X" to make it a bit less odd? Otherwise +1 to what was said above.

**Comment by glebm** [comment]
The name is "DevilutionX", without a space, and it has been the name for many years.
The name in FlatHub should not be different from the actual name.

**Comment by tsunamistate** [comment]
> usually we don't like dark outlines, as they don't contrast with dark backgrounds

I don't really understand this rule. As anyone who watches films with subtitles can attest, that best visibility is bright colour with dark outline.

Your tool with canvas lines did make it clear, that the icon is off-centre. I'm fine with shrinking it a bit, and properly centreing it.
Where can I check the icon for these lines, while editing it?

**Comment by razzeee** [comment]
> Your tool with canvas lines did make it clear, that the icon is off-centre. I'm fine with shrinking it a bit, and properly centreing it. Where can I check the icon for these lines, while editing it?

Download the SVG template from here https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#reasonable-footprint and use it in your design file, while editing.

**Comment by tsunamistate** [comment]
@bertob @razzeee Sorry for procrastinating on this for so long

Here's the progress update:

* Text updates (add brand colours and reword summary) are already upstream: https://github.com/diasurgical/DevilutionX/pull/7756 and I'm merging them into Flathub repo right now: https://github.com/flathub/org.diasurgical.DevilutionX/pull/11
* Minimal logo changes (shrink and centre the logos) are in PR: https://github.com/diasurgical/DevilutionX/pull/7786. Ideally, I would've liked to remove the red background and leave just the skull, but that's beyond my skill set
* There's also a proposal by @Ajenbo to use an icon we use for mobile version

![Image](https://github.com/user-attachments/assets/b0cfefa1-409c-4f75-b609-acfb582a9e2a)

but that will change the icons for ALL platforms we ship, and I personally don't like the red background

**Comment by razzeee** [comment]
Yeah, not thrilled about the red background, it would need to comply with the `Doesn't fill too much or too little of the canvas: I don't get it, please help` rule anyway - which would need further editing. 

But if you shrink that down to have a transparent border and maybe round the edges - it would allow us to fix the failing dark/light check.

Then again, I think if everything else passes, we could also waive the dark check in this case, as it's a game in addition.

**Comment by AJenbo** [comment]
Lets not change our icons and name everywhere just because Flathub doesn't find them fashionable. 

#### Icon

Instead of changing icons universally, it would make more sense to add a Flathub-specific variation if required. If the icon is only for their download page, why not just use the Android version and move on? Users will only see it briefly anyway.

#### Name Styling

Flathub’s approach to compound names seems inconsistent with broader industry standards. Many well-known platforms use uppercase formatting for the second word (e.g., GitHub, HubSpot, TechHub, DataHub, StartupHub, HealthHub). It’s unclear why Flathub insists on merging them into a single word or adding spacing.

#### Highlight Colors

The purpose of the highlight colors is unclear to me, and the suggested ones aren’t particularly appealing. Why present a game about fighting the devil on a salmon pink background? The dark color even seems to violate Flathub’s rule against blending with the icon. Does Flathub not have some sane defaults for light and dark themes? Once installed, programs will appear in a system menu with a common color. So why not use a common color in the app store as well?

#### Screenshot Consistency

This might be a bit off-topic, but looking through the Flathub site, there’s noticeable inconsistency in whether apps are depicted in light or dark mode. Requiring a screenshot in both modes would add value for users by showing how the app will actually look once installed. However, from what I can tell, this isn’t something mentioned in their style guide.

**Comment by AJenbo** [comment]
> But if you shrink that down to have a transparent border and maybe round the edges - it would allow us to fix the failing dark/light check.

That sounds fine. This happens automatically on Android, it uses different shapes masks depending on the context which is why it's fully extended in the actual image file.

**Comment by AJenbo** [comment]
It would also be nice if FlatHub could fix this:

![Image](https://github.com/user-attachments/assets/5b79203b-e96d-43e2-a34a-2536881e4af6)

It's ironic that if you click links you get this:

![Image](https://github.com/user-attachments/assets/c8b4ccfe-c158-4a6e-b3a0-8947ed90a635)

From what I understand it's because the Sustainable Use License isn't a known one to Flathub, but saying that we aren't doing development in the open is just flat out false. The license model seems a really dumb way to determine if source is available or not. The whole build process happens in the public and there are no secret bits, the builds are reproducible.

**Comment by razzeee** [comment]
Well, you're saying that it's proprietary here https://github.com/diasurgical/DevilutionX/blob/master/Packaging/nix/devilutionx.metainfo.xml#L13

Not sure if the spdx identifier for your license exists, but it should be easy to figure out.

**Comment by tsunamistate** [comment]
> Not sure if the spdx identifier for your license exists, but it should be easy to figure out.

It doesn't, which is why I had to fill in proprietary
Here's the licence we use: https://github.com/diasurgical/DevilutionX/blob/master/LICENSE.md lifted from here: https://docs.n8n.io/sustainable-use-license/

**Comment by razzeee** [comment]
> Lets not change our icons and name everywhere just because Flathub doesn't find them fashionable.
> #### Icon
> 
> Instead of changing icons universally, it would make more sense to add a Flathub-specific variation if required. If the icon is only for their download page, why not just use the Android version and move on? Users will only see it briefly anyway.

It's not only the download page, it's what's used your system too.

> #### Highlight Colors
> 
> The purpose of the highlight colors is unclear to me, and the suggested ones aren’t particularly appealing. Why present a game about fighting the devil on a salmon pink background? The dark color even seems to violate Flathub’s rule against blending with the icon. Does Flathub not have some sane defaults for light and dark themes? Once installed, programs will appear in a system menu with a common color. So why not use a common color in the app store as well?

These are only for highlight banners so far - see https://flathub.org/apps/org.diasurgical.DevilutionX/bannerpreview
This one right now has a placeholder color, to make it clear, that you should set an actual color. If you don't do that, we won't use that feature.

> #### Screenshot Consistency
> 
> This might be a bit off-topic, but looking through the Flathub site, there’s noticeable inconsistency in whether apps are depicted in light or dark mode. Requiring a screenshot in both modes would add value for users by showing how the app will actually look once installed. However, from what I can tell, this isn’t something mentioned in their style guide.

There is support for marking apps like that in appstream, so it's possible. But hard to do with static web page rendering, as the client color is only available, when somebody opens the webpage.

**Comment by razzeee** [comment]
> > Not sure if the spdx identifier for your license exists, but it should be easy to figure out.
> 
> It doesn't, which is why I had to fill in proprietary Here's the licence we use: [diasurgical/DevilutionX@`master`/LICENSE.md](https://github.com/diasurgical/DevilutionX/blob/master/LICENSE.md?rgh-link-date=2025-02-27T16%3A59%3A07.000Z) lifted from here: [docs.n8n.io/sustainable-use-license](https://docs.n8n.io/sustainable-use-license/)

Did you write a request for it on https://github.com/spdx/license-list-XML/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen ? I can't find one.

**Comment by hfiguiere** [comment]
> > Not sure if the spdx identifier for your license exists, but it should be easy to figure out.
> 
> It doesn't, which is why I had to fill in proprietary Here's the licence we use: https://github.com/diasurgical/DevilutionX/blob/master/LICENSE.md lifted from here: https://docs.n8n.io/sustainable-use-license/

The list is here https://spdx.org/licenses/

**Comment by razzeee** [comment]
You can also add the license file like this https://github.com/flathub/com.spotify.Client/blob/0187fe4fe523d8f1a3f41104c635fffbd4e6b09a/com.spotify.Client.appdata.xml#L10 but that also won't stop it from saying proprietary.

**Comment by AJenbo** [comment]
> Well, you're saying that it's proprietary here https://github.com/diasurgical/DevilutionX/blob/master/Packaging/nix/devilutionx.metainfo.xml#L13

We also state that it's developed in the open here: https://github.com/diasurgical/DevilutionX/blob/master/Packaging/nix/devilutionx.metainfo.xml#L23

**Comment by ephphatha** [comment]
> You can also add the license file like this https://github.com/flathub/com.spotify.Client/blob/0187fe4fe523d8f1a3f41104c635fffbd4e6b09a/com.spotify.Client.appdata.xml#L10 but that also won't stop it from saying proprietary.

SPDX license identifiers allow for user defined license references, does flathub support that? https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines#license implies that only SPDX License List Short Form Identifiers or the specific user-defined license reference `LicenseRef-proprietary` are acceptable. While waiting for SPDX/n8n to add this license to the license list we could use `LicenseRef-scancode-sustainable-use-1.0` (from https://scancode-licensedb.aboutcode.org/sustainable-use-1.0.html) for something likely to be recognised outside the project.

**Comment by razzeee** [comment]
I'm not sure that would pass the appstream validation, which is the main limiting factor. https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license

I think we need @bbhtt for that

**Comment by bbhtt** [comment]
>  SPDX license identifiers allow for user defined license references, does flathub support that?

Yes you should be able to use:

```xml
<project_license>LicenseRef-scancode-sustainable-use-1.0=https://scancode-licensedb.aboutcode.org/sustainable-use-1.0.html</project_license>
```

> Maybe there could be an option for "unknown" or "custom" as the license if it doesn't happen to be on spdx

The website has "special" license for this, using the above tag will give you a "special" license in the UI. Eg. https://flathub.org/apps/com.gitbutler.gitbutler

**Comment by AJenbo** [comment]
Thanks that's very acceptable.

**Comment by tsunamistate** [comment]
FYI, I have made changed the licence to the one suggested: `<project_license>LicenseRef-scancode-sustainable-use-1.0=https://scancode-licensedb.aboutcode.org/sustainable-use-1.0.html</project_license>`

https://github.com/flathub/org.diasurgical.DevilutionX/pull/13
https://github.com/diasurgical/DevilutionX/pull/7802

Thank you for your help with this!

**Comment by tsunamistate** [comment]
To update this issue, there's only 2 quality problems left to resolve:

1. Name. `No weird formatting, punctuation, lowercase, etc.` See comment above


> #### Name Styling
> 
> Flathub’s approach to compound names seems inconsistent with broader industry standards. Many well-known platforms use uppercase formatting for the second word (e.g., GitHub, HubSpot, TechHub, DataHub, StartupHub, HealthHub). It’s unclear why Flathub insists on merging them into a single word or adding spacing.

2. Icon. `Doesn't fill too much or too little of the canvas` and `Good contrast on dark backgrounds` I have sent a reminder to @AJenbo to look into this

**Comment by AJenbo** [comment]
@razzeee do you think we will be granted an exception regarding the name so we don't have to have a different branding on Flatup?

**Comment by razzeee** [comment]
> [@razzeee](https://github.com/razzeee) do you think we will be granted an exception regarding the name so we don't have to have a different branding on Flatup?

we'll likely do that, but shouldn't change much, when the icon still fails

**Comment by AJenbo** [comment]
Sure, but we’d prefer not to change the icon if the issue is ultimately tied to the name. The current icon matches the dimensions the game has used since the 90s, and changing it just for Flathub would mean altering it across multiple distribution channels and platforms.

It would be helpful to confirm whether changing the icon would actually resolve the issue, rather than risking rejection again and having to revert the change.

**Comment by razzeee** [comment]
If you fix the icon, I will pass the name review too.

You don't have to redo the icon completely, the problem the black border (white border would cause the same problem) as it would change footprint size, depending on if you run your system in light or dark mode.

The other problem is about the icon not being centered and it being too big.

<img width="629" height="282" alt="Image" src="https://github.com/user-attachments/assets/46a1fe52-5117-4867-8701-1526992b1780" />

**Comment by AJenbo** [comment]
The plan is to bring it more in line with the Android icon, though since the format doesn’t support dynamic elements, we’ll still need to adjust a few things.

Regarding the centering: The icon isn’t symmetrical, it's centered around the skull’s face, while the background rectangle is intentionally offset to create perspective depth and show the skull’s right side. This doesn't seems like it violates any of the icon guidelines and is similar to other icons.

I'll try to get a new icon pushed next month.

**Comment by razzeee** [comment]
> Regarding the centering: The icon isn’t symmetrical, it's centered around the skull’s face, while the background rectangle is intentionally offset to create perspective depth and show the skull’s right side. This doesn't seems like it violates any of the icon guidelines and is similar to other icons.

I think I did get the artistic intend, but it feels kinda off to me in my system, as it leads to weird spacings.

E.g.

<img width="565" height="215" alt="Image" src="https://github.com/user-attachments/assets/b2f7cd39-d7ff-4919-b8e0-d389b6e1be61" />

<img width="1258" height="127" alt="Image" src="https://github.com/user-attachments/assets/4cf330df-4dde-4d47-a0ad-bd75fbbe6262" />

(not trying to say, the other icons are perfect)

**Comment by AJenbo** [comment]
This is what the Android icon looks like:

<img width="124" height="126" alt="Image" src="https://github.com/user-attachments/assets/7ad9837e-a150-4a1a-9b5e-5b33575e9b40" />

**Comment by razzeee** [comment]
That should be fine, as long as it doesn't fill the whole canvas and is centered

**Comment by AJenbo** [comment]
@razzeee this issue should now be solved

**Comment by tsunamistate** [comment]
@razzeee so, the 1.5.5 release has been deployed, and it can be downloaded from Flathub in stores, version is shown as 1.5.5, however, the Flathub page still shows old icon and release notes:

<img width="1918" height="951" alt="Image" src="https://github.com/user-attachments/assets/8481b1c5-2908-414b-9e27-7444aefb57e5" />
<img width="1920" height="940" alt="Image" src="https://github.com/user-attachments/assets/a9518ed3-4941-469f-baff-618cd33c2569" />

Weirdly, in search, new icon is already shown:

<img width="1920" height="604" alt="Image" src="https://github.com/user-attachments/assets/eacca6d4-f330-49ef-8cc1-82ce34ac24e9" />

Could you please take a look?

**Comment by razzeee** [comment]
Caches just need some time to invalidate for pages with higher views

**Comment by tsunamistate** [comment]
Page has been updated with new release
I have sent a request to re-review the quality guideline checks, could you please mark them as passing @razzeee ?

**Comment by razzeee** [comment]
Looking nice, thank you

**Comment by tsunamistate** [comment]
Thank you for your patience!

<img width="1920" height="956" alt="Image" src="https://github.com/user-attachments/assets/c528b2cc-11a5-4343-8883-652badf76639" />

Closing as resolved
