### ISSUE TITLE
OBS Studio flathub page not working, reports status 500

### ISSUE THREAD

**Issue by fiftydinar** [flathub/flathub#6155]
Installing OBS from command-line or through Gnome Software works, but flathub page isn't working:

![Image](https://github.com/user-attachments/assets/63d9bef8-868a-460a-b3d1-a7d09f3916e5)

Flathub homepage & pages of other apps works.

**Comment by razzeee** [comment]
One of the addons seems to return without ids - I'm still trying to figure out why. Might be an eol addon - not sure yet.

**Comment by razzeee** [comment]
The addon endpoint seems to return `com.obsproject.Studio.Plugin.NDI` which is an eoled app.

**Comment by razzeee** [comment]
https://github.com/flathub-infra/website/pull/4650 should fix it, but it's not really correct.

The real problem is, that the new way we determine eoled apps, isn't branch sensitive. So that data is useless for addons, sdks etc

**Comment by MrStickyPiston** [comment]
Same issue for Breeze Gtk: https://flathub.org/apps/org.gtk.Gtk3theme.Breeze, but this is not solved.

![Image](https://github.com/user-attachments/assets/88104a11-d272-4bdd-bea6-29133def7381)

**Comment by hfiguiere** [comment]
1. it's not the same issue if it is a different package
2. themes are not listed so it works as intended.
